### ISSUE TITLE
Import lacking date selector, poor formatting

### ISSUE THREAD

**Issue by devinchristianson** [devinchristianson/COS397#22]
Formatting: This page needs to be centered w/ proper font etc
Date selector: While we're improving formatting, is there a reason the "date" field on import doesn't use a date selector? If not, we should switch that over, so we aren't relying on the user inputting a proper date.

**Comment by NickKania** [comment]
The data contains a date collected field that we can use rather than having the user specify.

**Comment by devinchristianson** [comment]
I think we still might as well collect a date from them as well, tho we can revisit this next time we meet. For now, I've added a date selector in PR #24
